[package]
name = "fxhash"
version = "0.1.0"
authors = ["cbreeden <github@u.breeden.cc>"]

[lib]
name = "fxhash"
path = "lib.rs"

[[bench]]
name = "fxhash"
path = "bench.rs"

[dependencies]
byteorder = "1.0.0"

[dev-dependencies]
seahash = "3.0.5"
fnv = "1.0.5"