# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=static_map_macros

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
    - env: TARGET=i686-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
      rust: nightly

    # Other architectures
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=mips-unknown-linux-gnu
      rust: nightly
    - env: TARGET=mips64-unknown-linux-gnuabi64
      rust: nightly
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      rust: nightly
    - env: TARGET=mipsel-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc64le-unknown-linux-gnu
      rust: nightly
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      rust: nightly

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
