[package]
name = "static-map"
version = "0.1.0"
authors = ["Christopher Breeden <github@u.breeden.cc>"]

[dependencies]
phf="0.7"
fxhash = { path = "fxhash" }
staticmap = { path = "staticmap" }
staticmap-builder = { path = "staticmap-builder" }
fnv = "1.0"