[package]
name = "staticmap-macros"
version = "0.1.0"
authors = ["Christopher Breeden <github@u.breeden.cc>"]

[dependencies]
syn = "*"
quote = "*"
itoa = "*"

[dependencies.fxhash]
path = "../fxhash"

[lib]
proc-macro = true

[[bin]]
path = "tests/build.rs"
name = "test"